default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

# 1. Swift-lint
  desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
  lane :dev_lint do
   	swiftlint(
		mode: :lint,
		executable: "Pods/SwiftLint/swiftlint",
		reporter: "html",
		output_file: "fastlane/swiftlint-results.html",
		config_file: '.swiftlint.yml',
		ignore_exit_status: true
	)
  end
end
